[package]
name = "pdfrip"
version = "2.0.0"
edition = "2021"
authors = ["Mufeed VH <contact@mufeedvh.com>", "Pommaq"]

[dependencies]
pdf = "0.7.2"
indicatif = "0.16.2"
clap = { version = "3.0.14", features = ["derive", "cargo"] }
colored = "2.0.0"
log = "0.4.19"
bus = "2.4.0"
anyhow = "1.0.72"
crossbeam = "0.8.2"
pretty_env_logger = "0.5.0"

[profile.release]
lto = 'thin'
panic = 'abort'
codegen-units = 1
