[package]
name = "pdfrip"
version = "1.0.0"
edition = "2021"

[dependencies]
pdf = "0.7.2"
rayon = "1.5.1"
indicatif = "0.16.2"
clap = "3.0.14"
colored = "2.0.0"
[target.'cfg(not(target_os = "windows"))'.dependencies]
snmalloc-rs = "0.2.28"

[profile.release]
lto = 'thin'
panic = 'abort'
codegen-units = 1
