[package]
name = "pdfrip"
version = "2.0.0"
edition = "2021"
authors = ["Mufeed VH <contact@mufeedvh.com>", "Pommaq"]

[dependencies]
pdf = "0.7.2"
rayon = "1.5.1"
indicatif = "0.16.2"
clap = { version = "3.0.14", features = ["derive", "cargo"] }
colored = "2.0.0"
log = "0.4.19"
env_logger = "0.10.0"
bus = "2.4.0"
anyhow = "1.0.72"
crossbeam = "0.8.2"
[target.'cfg(not(target_os = "windows"))'.dependencies]
snmalloc-rs = "0.2.28"

[profile.release]
lto = 'thin'
panic = 'abort'
codegen-units = 1
